cmake_minimum_required(VERSION 3.27...3.30)
project(cobweb LANGUAGES CXX)

# Nanobind loading
if(CMAKE_VERSION VERSION_LESS 3.18)
  set(DEV_MODULE Development)
else()
  set(DEV_MODULE Development.Module)
endif()

find_package(
  Python 3.8
  COMPONENTS Interpreter ${DEV_MODULE}
  REQUIRED)

if(NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)
  set(CMAKE_BUILD_TYPE
      Release
      CACHE STRING "Choose the type of build." FORCE)
  set_property(CACHE CMAKE_BUILD_TYPE PROPERTY STRINGS "Debug" "Release"
                                               "MinSizeRel" "RelWithDebInfo")
endif()

execute_process(
  COMMAND "${Python_EXECUTABLE}" -m nanobind --cmake_dir
  OUTPUT_STRIP_TRAILING_WHITESPACE
  OUTPUT_VARIABLE nanobind_ROOT)
find_package(nanobind CONFIG REQUIRED)

# Loading Eigen
find_package(Eigen3 REQUIRED)

# Build Cobweb
nanobind_add_module(cobweb_discrete src/cobweb_discrete.cpp src/helper.cpp)
target_include_directories(cobweb_discrete PRIVATE include/)
target_link_libraries(cobweb_discrete PRIVATE Eigen3::Eigen)
target_compile_features(cobweb_discrete PRIVATE cxx_std_17)
install(TARGETS cobweb_discrete DESTINATION cobweb)

nanobind_add_module(
  cobweb_continuous src/cobweb_continuous.cpp src/cobweb_continuous_node.cpp
  src/cobweb_continuous_tree.cpp src/helper.cpp)
target_include_directories(cobweb_continuous PRIVATE include/)
target_link_libraries(cobweb_continuous PRIVATE Eigen3::Eigen)
target_compile_features(cobweb_continuous PRIVATE cxx_std_17)
install(TARGETS cobweb_continuous DESTINATION cobweb)

# nanobind_add_module(
#   dev_cobweb_continuous src/dev_cobweb_continuous.cpp src/dev_cobweb_continuous_node.cpp
#   src/dev_cobweb_continuous_tree.cpp src/helper.cpp)
# target_include_directories(dev_cobweb_continuous PRIVATE include/)
# target_link_libraries(dev_cobweb_continuous PRIVATE Eigen3::Eigen)
# target_compile_features(dev_cobweb_continuous PRIVATE cxx_std_17)
# install(TARGETS dev_cobweb_continuous DESTINATION cobweb)
